# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PowerSpectrum.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.resize(1280, 800)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView_D = GraphicsLayoutWidget(self.tab)
        self.graphicsView_D.setObjectName("graphicsView_D")
        self.gridLayout_2.addWidget(self.graphicsView_D, 4, 2, 1, 2)
        self.graphicsView_R = GraphicsLayoutWidget(self.tab)
        self.graphicsView_R.setObjectName("graphicsView_R")
        self.gridLayout_2.addWidget(self.graphicsView_R, 4, 0, 1, 2)

        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 1)

        self.pushButton2 = QtWidgets.QPushButton(self.tab)
        self.pushButton2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton2, 3, 1, 1, 1)

        self.pushButton3 = QtWidgets.QPushButton(self.tab)
        self.pushButton3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton3, 3, 2, 1, 1)

        self.pushButton4 = QtWidgets.QPushButton(self.tab)
        self.pushButton4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton4, 3, 3, 1, 1)

        self.label = QtWidgets.QLabel(self.tab)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 3, 1, 1)
        self.lineEdit_R = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_R.setObjectName("lineEdit_R")
        self.gridLayout_2.addWidget(self.lineEdit_R, 2, 0, 1, 1)
        self.lineEdit_D = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_D.setObjectName("lineEdit_D")
        self.gridLayout_2.addWidget(self.lineEdit_D, 2, 1, 1, 1)
        self.label_R = QtWidgets.QLabel(self.tab)
        self.label_R.setObjectName("label_R")
        self.gridLayout_2.addWidget(self.label_R, 0, 0, 1, 1)
        self.label_D = QtWidgets.QLabel(self.tab)
        self.label_D.setObjectName("label_D")
        self.gridLayout_2.addWidget(self.label_D, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FFT Magnitude"))
        self.pushButton.setText(_translate("Form", "Ref"))
        self.pushButton2.setText(_translate("Form", "LR"))
        self.pushButton3.setText(_translate("Form", "MR"))
        self.pushButton4.setText(_translate("Form", "SR"))

        self.label_R.setText(_translate("Form", "Frequency Index [R]"))
        self.label_D.setText(_translate("Form", "Frequency Index [D]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "1d slice"))
from pyqtgraph import GraphicsLayoutWidget
