#ifndef _THREAD_MANAGER_CFG_H
#define _THREAD_MANAGER_CFG_H
/*
#define TASKMGR_RSM_TASK_STACKSIZE (configMINIMAL_STACK_SIZE * 32)
#define TASKMGR_SNR_IMU_TASK_STACKSIZE (configMINIMAL_STACK_SIZE * 8)
#define TASKMGR_SNR_GPS_TASK_STACKSIZE (configMINIMAL_STACK_SIZE * 8)
#define TASKMGR_NET_TASK_STACKSIZE (configMINIMAL_STACK_SIZE * 32)
#define TASKMGR_RSP_TASK_STACKSIZE (configMINIMAL_STACK_SIZE * 60)
#define TASKMGR_SCHD_TASK_STACKSIZE (configMINIMAL_STACK_SIZE * 8)
#define TASKMGR_TASK_STACKSIZE 		(configMINIMAL_STACK_SIZE * 8)
#define TASKMGR_NET_ETHSTACK_STACKSIZE (configMINIMAL_STACK_SIZE * 32)
#define TASKMGR_NET_APP_TASK_STACKSIZE (configMINIMAL_STACK_SIZE * 32)
#define TASKMGR_FLOG_TASK_STACKSIZE (configMINIMAL_STACK_SIZE * 60)
#define TASKMGR_CAM_TASK_STACKSIZE (configMINIMAL_STACK_SIZE * 8)
*/
#define tskIDLE_PRIORITY			( 0U )

#define TASKMGR_RSM_TASK_PRIORITY 	(tskIDLE_PRIORITY + 15)	// realtime
#define TASKMGR_SCHD_TASK_PRIORITY 	(tskIDLE_PRIORITY + 14)
#define TASKMGR_CAM_TASK_PRIORITY (tskIDLE_PRIORITY + 14)	// realtime
#define TASKMGR_RSP_SLTRIG_TASK_PRIORITY (tskIDLE_PRIORITY + 13) // realtime
#define TASKMGR_SNR_IMU_TASK_PRIORITY	(tskIDLE_PRIORITY + 12)	// realtime
#define TASKMGR_SNR_GPS_TASK_PRIORITY	(tskIDLE_PRIORITY + 6)	// realtime
#define TASKMGR_VCOMM_TASK_PRIORITY	(tskIDLE_PRIORITY + 7)	// realtime
#define TASKMGR_NET_ETHMACINPUT_TASK_PRIORITY 	(tskIDLE_PRIORITY + 12) // 6
#define TASKMGR_NET_ETHSTACK_TASK_PRIORITY 		(tskIDLE_PRIORITY + 11) // 7
#define TASKMGR_NET_TASK_PRIORITY 				(tskIDLE_PRIORITY + 10)
#define TASKMGR_NET_APP_APPLCOMM_TASK_PRIORITY    (tskIDLE_PRIORITY + 10)
#define TASKMGR_NET_APP_APPLCOMM_TXTASK_PRIORITY    (tskIDLE_PRIORITY + 10)
#define TASKMGR_NET_APP_APPLCOMM_RXTASK_PRIORITY    (tskIDLE_PRIORITY + 10)
#define TASKMGR_NET_COMM_APPLCMD_TASK_PRIORITY    (tskIDLE_PRIORITY + 9)
#define TASKMGR_NET_APP_LOGGER_TASK_PRIORITY    (tskIDLE_PRIORITY + 8)
#define TASKMGR_MMCTFTP_TASK_PRIORITY (tskIDLE_PRIORITY + 6)
#define TASKMGR_RSP_TASK_PRIORITY 	(tskIDLE_PRIORITY + 5)
#define TASKMGR_TASK_PRIORITY			( tskIDLE_PRIORITY + 3 )
#define TASKMGR_FLOG_TASK_PRIORITY ( tskIDLE_PRIORITY + 4 )
#define TASKMGR_BTSLOG_TASK_PRIORITY  (tskIDLE_PRIORITY + 4)


#define TASKMGR_RSM_TASK_TAG 1
#define TASKMGR_SNR_TASK_TAG 2
#define TASKMGR_SNR_BG_TASK_TAG 3
#define TASKMGR_RSP_TASK_TAG 4
#define TASKMGR_SCHD_TASK_TAG 5

#define TASKMGR_NET_ETHMACINPUT_TASK_TAG 10
#define TASKMGR_NET_ETHSTACK_TASK_TAG 11
#define TASKMGR_NET_TASK_TAG 12
#define TASKMGR_NET_APP_LOGGER_TASK_TAG 20
#define TASKMGR_NET_APP_FINDECU_TASK_TAG 21
#define TASKMGR_NET_APP_APPLCOMM_TASK_TAG 22

#endif